### Отримати всі відправлення
GET http://localhost:5036/postings


### Отримати відправлення за ID
GET http://localhost:5036/postings/1


### Створити нове відправлення
POST http://localhost:5036/postings
Content-Type: application/json

{
  "from": "Vlad",
  "to": "Ivan",
  "content": "Laptop",
  "deliveryType": 2,
  "weight": 2.5,
  "width": 35,
  "height": 25,
  "depth": 10,
  "value": 1000,
  "price": 50
}


### Оновити відправлення
PUT http://localhost:5036/postings/1
Content-Type: application/json

{
  "from": "Alice",
  "to": "Charlie",
  "content": "New Books",
  "deliveryType": 0,
  "weight": 3,
  "width": 35,
  "height": 25,
  "depth": 15,
  "value": 80,
  "price": 20
}


### Видалити відправлення
DELETE http://localhost:5036/postings/1

